app:
  self_origin_name: "server"
  log_file_path: "/tmp/server_handler.log"
  log_level: "INFO"

pubsub:
  type: "redis"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
  admine_channels_map:
    server_channel: "server_channel"
    command_channel: "command_channel"
    vpn_channel: "vpn_channel"

minecraft_server:
  runtime_type: "docker"
  server_up_timeout: "2m"
  server_off_timeout: "1m"
  server_command_exec_timeout: "30s"
  rcon_address: "127.0.0.1:25575"
  rcon_password: "password"
  docker:
    compose_path: "../minecraft_server/fabric/docker-compose.yaml"
    container_name: "mine_server"
    service_name: "mine_server"

web_server:
  host: "0.0.0.0"
  port: 3000
